dubbo:
  application:
    name: index
  registry:
    protocol: zookeeper
    address: 47.102.212.171:2181
server:
  port: 9091
spring:
  thymeleaf:
    cache: false
  redis:
    host: 47.102.212.171
    port: 6379
    jedis:
      pool:
        max-active: 20
    password: lhshop


fdfs:
  so-timeout: 1500
  connect-timeout: 600
  pool:
    jmx-enabled: false
  thumb-image:
    width: 200
    height: 100
  tracker-list: 47.102.212.171:22122

image:
  server: http://47.102.212.171/

