dubbo:
  application:
    name: background
  registry:
    protocol: zookeeper
    address: 47.102.212.171:2181
server:
  port: 9090
spring:
  thymeleaf:
    cache: false
    suffix: .html
    prefix: classpath:/templates/
    mode: LEGACYHTML5

fdfs:
  so-timeout: 1500
  connect-timeout: 600
  pool:
    jmx-enabled: false
  thumb-image:
    width: 200
    height: 100
  tracker-list: 47.102.212.171:22122

image:
  server: http://47.102.212.171/


